:consumer_key: mnPJ30hyksdITjmd8Eb4w
:consumer_secret: mfmU1mXv9kKrf3VWzBqM84xaqbQIB1wKSRPzEX7MZU
:oauth_token: 632269252-Rsld4h8o2w5gGDp8o8iLwBPI7Bign2lJkBhYv7iR
:oauth_token_secret: kIGCvw6fYftbHFsNrZsLPyhsEqX7b9LpX8tQaV5e0
